import java.io.IOException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author SANDEEP
 */
public class What2DoUI extends javax.swing.JFrame {

	/**
	 * Creates new form What2DoUI
	 */
	public What2DoUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane6 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jTabbedPane2 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		textField1 = new java.awt.TextField();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextPane2 = new javax.swing.JTextPane();
		jTabbedPane3 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jPanel5 = new javax.swing.JPanel();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jPanel6 = new javax.swing.JPanel();
		jScrollPane7 = new javax.swing.JScrollPane();
		jTextArea4 = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane6.setViewportView(jTable1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		textField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		textField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		textField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textField1ActionPerformed(evt);
			}
		});
		textField1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				try {
					textField1KeyTyped(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jTextPane2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
		jTextPane2
				.setText("FORMAT : [command]..[keywords]..[start time]..[end time]..[priority]..[r-reminder time]");
		jScrollPane4.setViewportView(jTextPane2);

		jTabbedPane3.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.RAISED));

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setBorder(new javax.swing.border.MatteBorder(null));
		jScrollPane2.setViewportView(jTextArea1);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 866,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96,
				Short.MAX_VALUE));

		jTabbedPane3.addTab("Upcoming Events", jPanel2);

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jTextArea2.setBorder(new javax.swing.border.MatteBorder(null));
		jScrollPane3.setViewportView(jTextArea2);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 866,
				Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 96,
				Short.MAX_VALUE));

		jTabbedPane3.addTab("Priority Events", jPanel4);

		jTextArea3.setColumns(20);
		jTextArea3.setRows(5);
		jTextArea3.setBorder(new javax.swing.border.MatteBorder(null));
		jScrollPane5.setViewportView(jTextArea3);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 866,
				Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 96,
				Short.MAX_VALUE));

		jTabbedPane3.addTab("Floating Events", jPanel5);

		jTextArea4.setColumns(20);
		jTextArea4.setRows(5);
		jTextArea4.setBorder(new javax.swing.border.MatteBorder(null));
		jScrollPane7.setViewportView(jTextArea4);

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 866,
				Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 96,
				Short.MAX_VALUE));

		jTabbedPane3.addTab("Search Results", jPanel6);

		jLabel2.setIcon(new javax.swing.ImageIcon("src\\Logo3.png")); // NOI18N
		jLabel2.setText("jLabel2");

		jLabel1.setIcon(new javax.swing.ImageIcon("src\\Logo5.png")); // NOI18N
		jLabel1.setText("jLabel1");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(28, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jTabbedPane3)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addGroup(
																				jPanel1Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								276,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								591,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addComponent(
																				textField1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jScrollPane4)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				128,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(22,
																				22,
																				22)
																		.addComponent(
																				jLabel1)))
										.addGap(1, 1, 1)
										.addComponent(
												textField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												34,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jTabbedPane3)));

		jPanel3.setBackground(new java.awt.Color(204, 204, 255));
		jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(
				0, 0, 0), 2, true));
		jPanel3.setForeground(new java.awt.Color(153, 180, 209));
		jPanel3.setToolTipText("Hello!");
		jPanel3.setName("What2Do"); // NOI18N
		jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3,
				javax.swing.BoxLayout.LINE_AXIS));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
						917, Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		jPanel3.getAccessibleContext().setAccessibleName("");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void textField1KeyTyped(java.awt.event.KeyEvent evt)
			throws IOException {// GEN-FIRST:event_textField1KeyTyped
		jTabbedPane3.setMnemonicAt(0, evt.VK_1);
		jTabbedPane3.setMnemonicAt(1, evt.VK_2);
		jTabbedPane3.setMnemonicAt(2, evt.VK_3);
		if (evt.getKeyChar() == '\n') {
			String data = textField1.getText();
			if (data.equals("exit") == true) {
				Executor.syncDatabase();
				System.exit(0);
			}
			Executor.analyze(data);
			String upcomingEvents = Executor.printDataBase();
			String priorityEvents = Executor.printPriorityDataBase();
			String floatingEvents = Executor.printFloatingDataBase();
			String searchResults = Executor.printSearchResults();
			upcomingEvents = format(upcomingEvents);
			priorityEvents = format(priorityEvents);
			floatingEvents = format(floatingEvents);
			searchResults = formatForSearch(searchResults);

			jTextArea1.setText(upcomingEvents);
			jTextArea2.setText(priorityEvents);
			jTextArea3.setText(floatingEvents);
			jTextArea4.setText(searchResults);
			textField1.setText("");

		}

		/*
		 * if (evt.getKeyChar()=='\n')
		 * jPanel5.setVisible(rootPaneCheckingEnabled);
		 */
	}// GEN-LAST:event_textField1KeyTyped

	private String format(String text) {
		String newText = "";
		newText += "Event ID\tName\tAdditional Details\n";
		for (int i = 0; i < text.length(); i++) {
			if (text.charAt(i) == '.' && text.charAt(i + 1) == '.') {
				newText += '\t';
				i++;
			} else {
				newText += text.charAt(i);
			}

		}
		// TODO Auto-generated method stub
		return newText;
	}
	
	private String formatForSearch(String text) {
		String newText = "";
		newText += "Index\tEvent ID\tName\tAdditional Details\n";
		for (int i = 0; i < text.length(); i++) {
			if (text.charAt(i) == '.' && text.charAt(i + 1) == '.') {
				newText += '\t';
				i++;
			} else {
				newText += text.charAt(i);
			}

		}
		// TODO Auto-generated method stub
		return newText;
	}


	private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textField1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 * @throws Exception 
	 */ 
	public static void main(String args[]) throws Exception {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(What2DoUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(What2DoUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(What2DoUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(What2DoUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new What2DoUI().setVisible(true);
				
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JTabbedPane jTabbedPane3;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextArea jTextArea4;
	private javax.swing.JTextPane jTextPane2;
	private java.awt.TextField textField1;
	// End of variables declaration//GEN-END:variables
}
